# Sử dụng Node.js 20.10.0 làm môi trường cơ bản
FROM node:20.10.0-alpine AS build_node

# Tạo thư mục làm việc trong container
WORKDIR /app

# Sao chép file package.json và package-lock.json vào container
COPY package*.json ./

# Cài đặt dependencies
RUN npm install

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Build ứng dụng nếu cần thiết (ví dụ với ứng dụng React hoặc Vue)
RUN npm run build

FROM nginx:alpine

COPY --from=build_node /app/dist /usr/share/nginx/html

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
# Expose cổng mà ứng dụng sẽ chạy (thường là 3000 hoặc 4000 tùy ứng dụng Node.js)
EXPOSE 80

# Lệnh khởi động ứng dụng Node.js
CMD ["nginx", "-g", "daemon off;"]