# docker-compose up --build
version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile_dev
    ports:
      - "3000:3000"  # Điều chỉnh cổng nếu cần
    environment:
      NODE_ENV: development
    command: npm run dev